### PR TITLE
DataStore types are more flexible.

### PR DESCRIPTION
**Pull request by FrostyNick**
I missed one important detail with `DataStore` loading data in general which I forgot to test. I made a few other changes as well:

Before this PR:
- Load and save data as JSON string.

After this PR:
- Load data as godot type (usually dictionary and mixed types) and data can be saved as JSON string or godot type.

The examples for saving in #8 now work as a result, and will make DataStore better to use.

I can also without too much difficulty also make loading data as a string too, but that's not a priority and not needed in most cases. I might include it in a future PR on the side if that is quick to do later.

If there's any new data to be saved I missed with this structure let me know! This is the structure that's returned when loading data for the first time. Note this ideally shouldn't be changed too often though to prevent breaking existing saves:

```gdscript
func _get_init_data():
	return {
		"data_ver":-99, # If data is incompatible with previous data, might want to increment this number
		#"hp": 100,
		"pos":{
			"x": -1,
			"y": -1
		},
		#"item_pos":{
			#{
				#"name": "coal",
				#"x": -1,
				#"y": -1
			#},
		#},
		"inventory":{
			"coal": 5,
			"coins": 0
		},
		#"terrain":2323 #seed??
	}
```

Also did: `git rm --cache */.godot -r`

Finally, this shouldn't create merge conflicts outside of Nick folder unless `.godot` folder is added and pushed afaik.

### CODE REVIEW

**Review by FrancisTR — APPROVED** [review]

**Comment by FrancisTR** [comment]
@FrostyNick There is a merge conflict base on my changes and it has to do with the .godot file. Can you please resolve it on your end?

**Comment by FrostyNick** [comment]
Should be ready to merge now @FrancisTR

**Comment by FrancisTR** [comment]
> Should be ready to merge now @FrancisTR

I made some updates. Can you try again @FrostyNick ?

**Comment by FrostyNick** [comment]
@FrancisTR Yes, resolved merge conflict

**Review by FrancisTR — APPROVED** [review]

**Pull request merged**
